import { Bot, CheckCircle2, Clock3, RefreshCw, Workflow, XCircle } from "lucide-react";
import { AppShell, PageHeader } from "@/components/rankcues-ui";
import { Notice, SourceBadge } from "@/components/rankcues-dashboard";
import { getAiProviderPublicStatus } from "@/lib/ai-provider";
import { getBacklinkProviderPublicStatus } from "@/lib/backlink-provider";
import { getAutomationOverview } from "@/lib/data-store";
import { getLocale, pick } from "@/lib/i18n";

export const dynamic = "force-dynamic";

export default async function AutomationsPage({ searchParams }: { searchParams: Promise<{ run?: string }> }) {
  const params = await searchParams;
  const [automation, ai, backlinks, locale] = await Promise.all([getAutomationOverview(), Promise.resolve(getAiProviderPublicStatus()), Promise.resolve(getBacklinkProviderPublicStatus()), getLocale()]);
  const failures = automation.runs.filter((run) => run.status === "failed").length;
  return (
    <AppShell active="/app/automations">
      <PageHeader kicker={pick(locale, "Collection engine", "数据采集引擎", "Motor de recopilación")} title={pick(locale, "One daily evidence pipeline, one weekly decision report", "每日自动收集证据，每周自动生成决策报告", "Evidencia diaria y un informe semanal de decisiones")} body={pick(locale, "GSC, GA4, page snapshots and backlinks are collected before AI analysis. Each run records row counts and exact errors for auditability.", "系统会在 AI 分析前收集 GSC、GA4、页面快照和外链；每次运行都会记录行数与具体错误，方便审计。", "GSC, GA4, capturas y enlaces se recopilan antes del análisis de IA, registrando filas y errores exactos.")} action={<form action="/api/automation/run" method="post"><button className="inline-flex h-9 items-center gap-2 rounded-lg bg-[#111827] px-3.5 text-[11px] font-semibold text-white"><RefreshCw size={13} /> {pick(locale, "Run full collection", "立即完整采集", "Ejecutar recopilación")}</button></form>} />
      <div className="grid gap-4 px-4 pb-8 sm:px-6 lg:px-8">
        {params.run === "completed" ? <Notice tone="success">Manual collection finished. Successful and failed source runs are recorded below.</Notice> : null}
        <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="data-card p-4"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#8b94a5]">Monitored sites</p><p className="mt-2 text-2xl font-semibold">{automation.monitoredSites}/{automation.activeSites}</p><p className="mt-1 text-[10px] text-[#8b94a5]">Active verified properties</p></div><div className="data-card p-4"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#8b94a5]">Recent runs</p><p className="mt-2 text-2xl font-semibold">{automation.runs.length}</p><p className="mt-1 text-[10px] text-[#8b94a5]">Latest 50 source jobs</p></div><div className="data-card p-4"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#8b94a5]">Failures</p><p className={`mt-2 text-2xl font-semibold ${failures ? "text-[#b42318]" : ""}`}>{failures}</p><p className="mt-1 text-[10px] text-[#8b94a5]">Visible, never silently skipped</p></div><div className="data-card p-4"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#8b94a5]">Weekly AI</p><p className="mt-2 text-2xl font-semibold">{ai.configured ? "Ready" : "Paused"}</p><p className="mt-1 text-[10px] text-[#8b94a5]">{ai.configured ? "Managed analysis service" : "Service temporarily unavailable"}</p></div></section>
        <section className="grid gap-4 xl:grid-cols-[360px_minmax(0,1fr)]"><div className="grid gap-4"><div className="data-panel p-5"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-[#eef1ff] text-[#5268d9]"><Clock3 size={17} /></span><div><p className="text-[11px] font-semibold">Daily evidence collection</p><p className="mt-1 font-mono text-[8px] text-[#98a2b3]">03:00 UTC · every day</p></div></div><ol className="mt-5 grid gap-3 text-[10px] text-[#667085]"><li>1. Search Console rankings and clicks</li><li>2. GA4 landing-page context</li><li>3. Page snapshots and material diffs</li><li>4. Backlink profile and link-level changes</li></ol></div><div className="data-panel p-5"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-[#eafbf6] text-[#087f6b]"><Bot size={17} /></span><div><p className="text-[11px] font-semibold">Weekly AI investigation</p><p className="mt-1 font-mono text-[8px] text-[#98a2b3]">04:00 UTC · Monday</p></div></div><div className="mt-5 grid gap-2 text-[9px]"><div className="flex justify-between"><span className="text-[#98a2b3]">{pick(locale, "Managed AI", "托管 AI", "IA gestionada")}</span><strong>{ai.configured ? pick(locale, "Active", "已启用", "Activa") : pick(locale, "Paused", "已暂停", "En pausa")}</strong></div><div className="flex justify-between"><span className="text-[#98a2b3]">{pick(locale, "Backlink add-on", "外链增值服务", "Complemento de enlaces")}</span><strong>{backlinks.configured ? pick(locale, "Active", "已启用", "Activo") : pick(locale, "Not enabled", "尚未启用", "No activado")}</strong></div></div></div></div>
          <div className="data-panel overflow-hidden"><div className="flex items-center justify-between border-b border-[#e7eaf0] px-5 py-4"><div><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#8b94a5]">Run history</p><h2 className="mt-1 text-base font-semibold">Collector diagnostics</h2></div><Workflow size={17} className="text-[#667085]" /></div><div className="max-h-[680px] divide-y divide-[#edf0f5] overflow-y-auto">{automation.runs.map((run) => <article key={run.id} className="grid gap-3 px-5 py-4 sm:grid-cols-[90px_minmax(0,1fr)_90px] sm:items-center"><div><SourceBadge source={run.source} /></div><div><div className="flex items-center gap-2"><span className={run.status === "completed" ? "text-[#087f6b]" : run.status === "failed" ? "text-[#b42318]" : "text-[#9a6700]"}>{run.status === "completed" ? <CheckCircle2 size={13} /> : run.status === "failed" ? <XCircle size={13} /> : <Clock3 size={13} />}</span><p className="truncate text-[10px] font-semibold">{run.siteUrl?.replace(/^sc-domain:/, "") || "System job"}</p></div><p className="mt-1 font-mono text-[8px] text-[#98a2b3]">{run.startedAt.toISOString().replace("T", " ").slice(0, 16)} UTC · {run.rowsWritten.toLocaleString()} rows</p>{run.error ? <p className="mt-2 text-[9px] leading-4 text-[#b42318]">{run.error}</p> : null}</div><span className="font-mono text-[8px] uppercase text-[#667085]">{run.completedAt ? "finished" : "running"}</span></article>)}{!automation.runs.length ? <div className="p-8 text-center text-[10px] text-[#667085]">No collection runs have been recorded.</div> : null}</div></div>
        </section>
      </div>
    </AppShell>
  );
}
